# Pseudonymisation versus Anonymisation {#pseudony_anony}

## Pseudonymisation 

*Pseudonymisation* is a de-identification process after which personal data can no longer be attributed to a specific data subject without the use of additional information. This process is also known as coding. It involves creating <u> **two separate files**</u>, one linking the personal data to the pseudonyms and another file which contains only the pseudonyms and the supplied research information. The former file is known as **a key file** or **code list** and must be kept separately from the latter file. 

The key file should be subjected to extra security measures (such as secured storage, password protection and encryption) to ensure that the identities of research participants are protected.

## Anonymisation

*Anonymisation* is another de-identification process which involves deleting direct and/or indirect identifiers from the data, such that there is no way to re-establish the link between individuals (research participants) and the research information they have supplied. In this case, there is <u>no key file</u>.



:::{.bubble}

*Pseudonymization* is employed to protect the identities of research participants by substituting direct identifiers with *pseudonyms*. This process is **reversible** and can still allow **re-identification**.

In contrast, *anonymisation* involves **deleting the identifiers**, rendering **re-identification impossible**, even by researchers themselves. The process is **irreversible**.
:::



<div class="two-column-box">
  <div class="column">
**Pseudonymization** 

It is employed to protect the identities of research participants by substituting direct identifiers with *pseudonyms*. This process is **reversible** and can still allow **re-identification**.
  </div>
  <div class="divider"></div>
  <div class="column">
**Anonymization**

It involves **deleting the identifiers**, rendering **re-identification impossible**, even by researchers themselves. The process is **irreversible**. 
  </div>
</div>

